# Generated by Django 2.2.2 on 2019-07-11 00:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, default=uuid.UUID('79968f9c-b09c-479a-be39-7c899afafe9c'), max_length=100, null=True, unique=True),
        ),
    ]
