# Generated by Django 2.2.2 on 2019-07-11 00:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190710_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, default=uuid.UUID('ee6228ba-e182-4d43-9916-06eb7cf70921'), max_length=100, null=True, unique=True),
        ),
    ]
