# Generated by Django 2.2.2 on 2019-07-11 02:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190710_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, default=uuid.UUID('e4a626d0-73a9-49f0-bcde-6acf04ba5a49'), max_length=100, null=True, unique=True),
        ),
    ]
