# Generated by Django 2.2.2 on 2019-06-23 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
