# Generated by Django 2.2.2 on 2019-06-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0002_auto_20190623_1800'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
