# Generated by Django 2.2.2 on 2019-07-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0003_auto_20190628_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
