# Generated by Django 2.2.2 on 2019-07-10 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0005_auto_20190710_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table=None,
        ),
    ]
