# Generated by Django 2.2.2 on 2019-07-11 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0006_auto_20190710_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
